version: '3'

services:
    web_server:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8001:80"
        volumes:
            - ./app:/var/www/html
        restart: always
        links:
            - db
    db:
        build:
            context: ./database
            dockerfile: Dockerfile
        volumes:
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password

volumes:
    db_data: